/* Tailwind Play CDN configuration (shared across every page).
   Colors/gradients/fonts map to the CSS variables in styles.css so that
   design tokens live in exactly one place (:root) with no hardcoded hex here. */
tailwind.config = {
  theme: {
    extend: {
      fontFamily: {
        sans: ['Space Grotesk', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'Menlo', 'monospace'],
      },
      colors: {
        bg: 'var(--bg)',
        elevated: 'var(--bg-elevated)',
        alt: 'var(--bg-alt)',
        header: 'var(--header)',
        text: 'var(--text)',
        muted: 'var(--text-muted)',
        dim: 'var(--text-dim)',
        soft: 'var(--text-soft)',
        cyan: 'var(--cyan)',
        magenta: 'var(--magenta)',
        'cyan-hover': 'var(--cyan-hover)',
        hair: 'var(--border)',
        'hair-soft': 'var(--border-soft)',
        'hair-12': 'var(--border-12)',
        'hair-cyan': 'var(--border-cyan)',
        'hair-magenta': 'var(--border-magenta)',
      },
      backgroundImage: {
        signature: 'var(--gradient)',
        rule: 'var(--rule)',
        stripe: 'var(--stripe)',
        'stripe-sm': 'var(--stripe-sm)',
        'art-1': 'var(--art-1)',
        'art-2': 'var(--art-2)',
        'art-3': 'var(--art-3)',
        'art-4': 'var(--art-4)',
        'art-5': 'var(--art-5)',
        'art-6': 'var(--art-6)',
        'chart-1': 'var(--chart-1)',
        'chart-2': 'var(--chart-2)',
        'chart-3': 'var(--chart-3)',
        'genre-1': 'var(--genre-1)',
        'genre-2': 'var(--genre-2)',
        'genre-3': 'var(--genre-3)',
        'genre-4': 'var(--genre-4)',
        'genre-5': 'var(--genre-5)',
        'genre-6': 'var(--genre-6)',
        'panel-tint': 'var(--panel-tint)',
        'card-scrim': 'var(--card-scrim)',
        'hero-scrim': 'var(--hero-scrim)',
        'hero-fade': 'var(--hero-fade)',
        'article-scrim': 'var(--article-scrim)',
      },
      borderRadius: {
        card: 'var(--r-card)',
        panel: 'var(--r-panel)',
        'panel-lg': 'var(--r-panel-lg)',
        btn: 'var(--r-btn)',
        chip: 'var(--r-chip)',
      },
      maxWidth: {
        shell: '1200px',
        'shell-wide': '1280px',
        prose: '1000px',
        article: '900px',
      },
      boxShadow: {
        overlay: '0 24px 60px rgba(0,0,0,0.5)',
        menu: '0 16px 40px rgba(0,0,0,0.5)',
      },
    },
  },
};
